<?php

module_load_include('inc', 'novartis_youtrack', 'novartis_youtrack.admin');
module_load_include('inc', 'novartis_youtrack', 'novartis_youtrack_link');



/*
 * Implements hook_menu()
 */
function novartis_youtrack_menu(){
    $items = array();

    $items['admin/config/content/youtrack'] = array(
        'title' => 'Novartis YouTrack Settings',
        'description' => 'Administer Novartis YouTrack settings',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('youtrack_admin_settings_form'),
        'access arguments' => array('administer youtrack settings'),
        'file' => 'novartis_youtrack.admin.inc',
    );

    $items['admin/config/content/youtrack/links'] = array(
        'title' => 'Link listing page',
        'description' => 'Choose the desired action to perform',
        'page callback' => 'youtrack_show_links',
        'access arguments' => array('access links page'),
        'file' => 'novartis_youtrack_link.inc',
        'type' => MENU_LOCAL_TASK
    );

    $items['admin/config/content/youtrack/tab1'] = array(
        'title' => 'Tab1',
        'description' => 'Tab 1',
        'page callback' => 'youtrack_show_links',
        'access arguments' => array('access links page'),
        'file' => 'novartis_youtrack_link.inc',
        'type' => MENU_LOCAL_TASK
    );

    return $items;
}


/**
 * Implements hook_permission()
 */
function novartis_youtrack_permission(){
    return array(
        'administer youtrack settings' => array(
            'title' => 'Administer YouTrack subscriptions',
            'description' => 'Allow users to administer YouTrack settings',
        ),
        'access links page' => array(
            'title' => 'Access the links page',
            'description' => 'Allow users to access the links page',
        ),
    );
}




/**
 * Implements hook_form_alter()
 */
function novartis_youtrack_form_alter(&$form, &$form_state, $form_id)
{
    if ($form_id == 'youtrack_admin_settings_form') {


        //dpm($form_state);
        //dpm($form);


        //add element to the fieldset
        $default_endpoint = variable_get('novartis_youtrack_endpoint', array());
        $default_username = variable_get('novartis_youtrack_username', array());
        $form['youtrack_endpoint']['#default_value'] = $default_endpoint;
        $form['youtrack_username']['#default_value'] = $default_username;
    }


}