<?php

module_load_include('inc', 'novartis_youtrack', 'novartis_youtrack.admin');


/*
 * Implements hook_menu()
 */
function novartis_youtrack_menu(){
    $items = array();

    $items['admin/config/content/youtrack'] = array(
        'title' => 'Novartis YouTrack Settings',
        'description' => 'Administer Novartis YouTrack settings',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('youtrack_admin_settings_form'),
        'access arguments' => array('administer youtrack settings'),
        'file' => 'novartis_youtrack.admin.inc',
    );

    return $items;
}


/**
 * Implements hook_permission()
 */
function novartis_youtrack_permission(){
    return array(
        'administer youtrack settings' => array(
            'title' => 'Administer YouTrack subscriptions',
            'description' => 'Allow users to administer YouTrack settings',
        ),
    );
}




/**
 * Implements hook_form_alter()
 */
function novartis_youtrack_form_alter(&$form, &$form_state, $form_id)
{
    if ($form_id == 'youtrack_admin_settings_form') {

        dpm($form_state);
        dpm($form);


        //add element to the fieldset
        $default_endpoint = variable_get('novartis_youtrack_endpoint', array());
        $default_username = variable_get('novartis_youtrack_username', array());
        $form['youtrack_endpoint']['#default_value'] = $default_endpoint;
    }
}